spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/uniqueDW/spring-cloud-parent
          search-paths: spring-cloud-config-project
server:
  port: 1201